### ISSUE TITLE
在NapCat-Desktop机器人列表下面添加可折叠的快捷

### ISSUE THREAD

**Issue by Hiraeth3000** [NapNeko/NapCatQQ-Desktop#11]
### 功能标题

新增一个可折叠的快捷打开日志

### 功能描述

希望在NapCat-Desktop列表下增加类似下图这样的可以折叠的机器人快捷图标，只显示已启动的机器人不显示未启动的机器人配置
![37966EF7A91C4F70F511A9C4FCA6E1D0](https://github.com/user-attachments/assets/08b41b43-f946-43e5-b51a-7171d6de3fd4)

### 功能的好处

查看多个机器人日志时不用先返回列表再切换另一个机器人

**Comment by HeartfeltJoy** [comment]
已实现 e37a6eeb1561782c2270b97a9c338823a46d61f5
