### ISSUE TITLE
[BUG] 我可以在这里跟你说晚安嘛

### ISSUE THREAD

**Issue by yongheng1014** [NapNeko/NapCatQQ-Desktop#13]
### 系统版本

win11pro

### NapCat Desktop 版本

1

### 发生了什么?

就是想给你个晚安iss

### 如何复现

你快说晚安

### 期望的结果?

晚安哦

### NapCat Desktop 运行日志

```shell
没有
```

**Comment by HeartfeltJoy** [comment]
晚安宝宝
