### ISSUE TITLE
[BUG] 下载不了NapCatQQ组件

### ISSUE THREAD

**Issue by XiaoFuOS** [NapNeko/NapCatQQ-Desktop#14]
### 系统版本

win server2019

### NapCat Desktop 版本

v1.0.4

### 发生了什么?

![QQ20241005-211755](https://github.com/user-attachments/assets/4d43f0bb-e4cc-4a44-b164-4a5b7dafbdf1)
![QQ20241005-211818](https://github.com/user-attachments/assets/4fafd8b3-3de1-42cc-b126-994d437469a2)

### 如何复现

下载404

### 期望的结果?

成功下载

**Comment by HeartfeltJoy** [comment]
该镜像站夜间无流量导致下载失败
