### ISSUE TITLE
[BUG] WindowsDefender 乱杀

### ISSUE THREAD

**Issue by MWTJC** [NapNeko/NapCatQQ-Desktop#17]
### 系统版本

Windows11 Pro Workstation 23H2

### NapCat Desktop 版本

2.6.27

### 发生了什么?

被Windows Defender乱杀导致desktop主程序崩掉，与此同时程序拉起的qq还在后台运行，附带造成收到一条消息就报一个错
![image](https://github.com/user-attachments/assets/93f1972b-653d-4563-a490-41a6fc9b33d4)

### 如何复现

defender自行扫描触发

### 期望的结果?

是否可能通过不同的Nuitka构建参数，或者自动添加defender白名单，给主程序洗白？

**Comment by HeartfeltJoy** [comment]
看看报的特征

**Comment by MWTJC** [comment]
> 看看报的特征

额需要我做啥（指不清楚佬是指的看啥特征，不是指的截图里的Trojan:Script/Wacatac.B!ml嘛？

**Comment by HeartfeltJoy** [comment]
这个问题归根结底不好解决，NapCat原理需要hook QQ，hook的特征不好抹除，解决方案也很简单，无非就是关闭杀软或者使用其他类似的项目

**Comment by MWTJC** [comment]
> 这个问题归根结底不好解决，NapCat原理需要hook QQ，hook的特征不好抹除，解决方案也很简单，无非就是关闭杀软或者使用其他类似的项目

明白了，我看到源码的环境依赖描述文件里，有nuitka，然后看到`Win32:Wacatac.B!ml`以为是nuitka打包的副作用，就以为可以通过使用更新版本的nuitka解决，
如果是hook造成那我直接手动加白名单就完事
