### ISSUE TITLE
[Feat] 支持NapCat本体Way5启动

### ISSUE THREAD

**Issue by 2455DD** [NapNeko/NapCatQQ-Desktop#5]
自从NapCat1.7.2开始支持Way5启动模式，且[NapCat-Installer](https://github.com/NapNeko/NapCat-Installer/blob/main/script/install.ps1)提供的启动模式也是Way5，然而当前NapCat-Desktop似乎并不支持Way5的启动模式，请考虑在下一版本添加Way5启动支持

**Comment by HeartfeltJoy** [comment]
最近比较忙,已适配至2.3.4🥰
